#! /usr/bin/env sh

# Install homebrew
command -v brew || /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

# Install stow and link dotfiles
command -v stow || brew install stow
stow --verbose --ignore=\.DS_Store --target ~ asdf
stow --verbose --ignore=\.DS_Store --target ~ macos
stow --verbose --ignore=\.DS_Store --target ~ vim
stow --verbose --ignore=\.DS_Store --target ~ zsh

# Install all other applications via homebrew
brew bundle --global

# Update applications from app store
mas upgrade

# Add asdf plugins
cut -d ' ' -f1 ~/.tool-versions | xargs -I % asdf plugin add %

# Install runtimes via asdf
asdf install

# Install iTerm shell integration
curl -L https://iterm2.com/shell_integration/install_shell_integration.sh | /bin/bash

# Configure MacOS
defaults write com.apple.finder AppleShowAllFiles YES
